// src/app/data/recipes.ts
import { Recipe } from '../interfaces/recipe.interface';

export const recipes: Recipe[] = [
  {
    id: 1,
    name: 'Fluffy Pancakes',
    description: 'Quick breakfast pancakes—light and fluffy.',
    images: ['assets/recipes/pancakes.jpg'],
    time: '20 min',
    difficulty: 'Easy',
    calories: 320,
    servings: 1,
    ingredients: [
      { name: 'All-purpose flour', qty: '1 cup' },
      { name: 'Sugar', qty: '2 tbsp' },
      { name: 'Baking powder', qty: '1 tsp' },
      { name: 'Baking soda', qty: '1/2 tsp' },
      { name: 'Salt', qty: 'pinch' },
      { name: 'Milk', qty: '3/4 cup' },
      { name: 'Egg', qty: '1' },
      { name: 'Melted butter', qty: '1 tbsp' },
    ],
    steps: [
      { title: 'Whisk dry ingredients', text: 'IN THE MUG' },
      { title: 'Whisk wet ingredients', text: 'TEXT' },
      { title: 'Combine', text: 'Mix until just lumpy.' },
      { title: 'Cook', text: '1/4 cup portions, 2–3 min per side.' },
    ],
    isFavorite: false,
    image: 'assets/recipes/pancakes.jpg',
    timeMinutes: 45,
    categoryIds: ['dinner', 'lunch', 'snacks', 'breakfast'],
  },
  {
    id: 2,
    name: 'Chicken Avocado Salad',
    description: 'Refreshing salad with grilled chicken and creamy avocado.',
    images: ['assets/recipes/chicken-salad.jpg'],
    time: '25 min',
    difficulty: 'Medium',
    calories: 450,
    servings: 2,
    ingredients: [
      { name: 'Chicken breasts', qty: '2' },
      { name: 'Avocado', qty: '1' },
      { name: 'Lettuce', qty: '2 cups' },
      { name: 'Red onion', qty: '1/2' },
      { name: 'Cherry tomatoes', qty: 'a handful' },
      { name: 'Olive oil', qty: 'to taste' },
      { name: 'Lemon juice', qty: 'to taste' },
      { name: 'Salt and pepper', qty: 'to taste' },
    ],
    steps: [
      { title: 'Cook chicken', text: 'Grill or pan-cook until golden.' },
      { title: 'Prep veggies', text: 'Slice avocado and vegetables.' },
      { title: 'Combine', text: 'Mix everything in a large bowl.' },
      { title: 'Dress', text: 'Olive oil + lemon juice, season to taste.' },
    ],
    isFavorite: false,
    image: 'assets/recipes/ChickAvoSalad.jpg',
    
    timeMinutes: 160,
    categoryIds: ['lunch', 'dinner'],
  },
  {
    id: 3,
    name: 'Spaghetti Bolognese',
    description: 'Classic Italian pasta with rich meat sauce.',
    images: ['assets/recipes/spaghetti.jpg'],
    time: '40 min',
    difficulty: 'Medium',
    calories: 600,
    servings: 2,
    ingredients: [
      { name: 'Spaghetti', qty: '200 g' },
      { name: 'Ground beef', qty: '250 g' },
      { name: 'Onion', qty: '1' },
      { name: 'Garlic cloves', qty: '2' },
      { name: 'Carrot', qty: '1' },
      { name: 'Canned tomatoes', qty: '400 g' },
      { name: 'Olive oil', qty: '1–2 tbsp' },
      { name: 'Salt, pepper, oregano', qty: 'to taste' },
    ],
    steps: [
      { title: 'Boil pasta', text: 'Cook until al dente.' },
      { title: 'Sauté base', text: 'Onion, garlic, carrot in oil.' },
      { title: 'Brown beef', text: 'Cook until no longer pink.' },
      { title: 'Simmer sauce', text: 'Add tomatoes; simmer ~20 min.' },
      { title: 'Serve', text: 'Toss or ladle sauce over pasta.' },
    ],
    isFavorite: false,
    image: 'assets/recipes/spagetiBolonjeze.jpg',
    timeMinutes: 45,
    categoryIds: ['lunch'],
  },
  {
    id: 4,
    name: 'Veggie Stir Fry',
    description: 'Colorful vegetables stir-fried with soy sauce.',
    images: ['assets/recipes/stirfry.jpg'],
    time: '15 min',
    difficulty: 'Easy',
    calories: 280,
    servings: 2,
    ingredients: [
      { name: 'Red bell pepper', qty: '1' },
      { name: 'Carrot', qty: '1' },
      { name: 'Zucchini', qty: '1' },
      { name: 'Broccoli florets', qty: '2 cups' },
      { name: 'Garlic', qty: '2 cloves' },
      { name: 'Ginger', qty: '1 tsp, grated' },
      { name: 'Soy sauce', qty: '2–3 tbsp' },
      { name: 'Oil', qty: '1 tbsp' },
    ],
    steps: [
      { title: 'Prep veg', text: 'Chop into bite-size pieces.' },
      { title: 'Heat pan', text: 'Add oil; sauté garlic/ginger briefly.' },
      { title: 'Stir-fry', text: 'Cook veg 5–7 min on high heat.' },
      { title: 'Finish', text: 'Add soy sauce and toss.' },
    ],
    isFavorite: false,
    image: 'assets/recipes/vegieStir.jpg',
    timeMinutes: 30,
    categoryIds: ['lunch', 'dinner'],
  },
  {
    id: 5,
    name: 'Mug Cake',
    description: 'Single-serving chocolate cake made in a mug.',
    images: ['assets/recipes/mugcake.jpg'],
    time: '10 min',
    difficulty: 'Easy',
    calories: 350,
    servings: 1,
    ingredients: [
      { name: 'Flour', qty: '4 tbsp' },
      { name: 'Sugar', qty: '2 tbsp' },
      { name: 'Cocoa powder', qty: '1 tbsp' },
      { name: 'Baking powder', qty: '1/4 tsp' },
      { name: 'Salt', qty: 'pinch' },
      { name: 'Milk', qty: '3 tbsp' },
      { name: 'Vegetable oil', qty: '1 tbsp' },
      { name: 'Vanilla', qty: '1/4 tsp' },
    ],
    steps: [
      { title: 'Mix dry', text: 'In a mug.' },
      { title: 'Add wet', text: 'Stir until combined.' },
      { title: 'Microwave', text: '70–90 seconds.' },
      { title: 'Rest', text: 'Cool slightly and eat.' },
    ],
    isFavorite: false,
    image: 'assets/recipes/mugCake.jpg',
    timeMinutes: 30,
    categoryIds: ['lunch', 'breakfast'],
  },
];
